#ifndef LXWM_STATE_H
#define LXWM_STATE_H

#include "wm_types.h"

extern Display *dpy;
extern int screen_num;
extern Window root;
extern Atom wm_delete;
extern Atom net_supported;
extern Atom net_wm_state;
extern Atom net_wm_state_fullscreen;
extern Atom net_active_window;
extern Atom net_current_desktop;
extern Atom net_number_of_desktops;
extern Atom net_client_list;
extern Atom net_client_list_stacking;
extern Atom net_workarea;

extern Monitor monitors[MAX_MONITORS];
extern int monitor_count;
extern Monitor *selmon;
extern Client *clients;
extern KeyBind keybinds[MAX_KEYBINDS];
extern int keybind_count;
extern Rule rules[MAX_RULES];
extern int rule_count;
extern ConfigVar config_vars[MAX_VARS];
extern int config_var_count;
extern int running;
extern int wm_restart_requested;
extern int bar_enabled;
extern int ipc_enabled;
extern int ipc_fd;
extern char ipc_socket_path[PATH_MAX];
extern int config_error_count;
extern WmLogLevel wm_log_level;
extern char wm_log_path[PATH_MAX];

extern unsigned long color_focus;
extern unsigned long color_unfocus;
extern unsigned long color_titlebar_focus;
extern unsigned long color_titlebar_unfocus;
extern unsigned long color_border_focus;
extern unsigned long color_border_unfocus;
extern unsigned long color_bg;
extern unsigned long color_fg;
extern unsigned long color_bar_mid;
extern unsigned long color_ws_active;
extern unsigned long color_ws_inactive;
extern unsigned long color_ws_urgent;
extern GC bar_gc;
extern XFontStruct *bar_font;
extern char wm_font_name[256];
extern int wm_font_size;
extern unsigned int primary_mod_mask;
extern double cpu_usage_pct;
extern int mem_usage_pct;
extern int wifi_strength_pct;
extern int wifi_link_up;
extern int ethernet_link_up;
extern char ethernet_iface[64];
extern char wifi_iface[64];
extern char ip_addr[64];
extern int ip_link_up;
extern int battery_pct;
extern int cpu_temp_c;
extern double disk_used_gb;
extern double disk_avail_gb;
extern double disk_total_gb;
extern unsigned long long last_cpu_total;
extern unsigned long long last_cpu_idle;
extern time_t last_stats_update;
extern int bar_ws_gap;
extern int bar_ws_pad_x;
extern int bar_ws_pad_y;
extern int bar_divider_min_w;
extern int bar_ws_slot_w;
extern int bar_right_zone_min_w;
extern int bar_module_slot_w;
extern int bar_modules_order[BAR_MOD_COUNT];
extern int bar_modules_count;
extern char bar_module_sep[32];
extern int bar_module_gap;
extern char bar_cpu_fmt[96];
extern char bar_mem_fmt[96];
extern char bar_time_fmt[96];
extern char bar_wifi_fmt[96];
extern char bar_ethernet_fmt[96];
extern char bar_ip_fmt[96];
extern char bar_battery_fmt[96];
extern char bar_cputemp_fmt[96];
extern char bar_disk_fmt[96];
extern char bar_disk_mode[16];
extern char bar_disk_path[128];
extern unsigned long bar_cpu_color;
extern unsigned long bar_mem_color;
extern unsigned long bar_time_color;
extern unsigned long bar_wifi_color;
extern unsigned long bar_wifi_down_color;
extern unsigned long bar_ethernet_color;
extern unsigned long bar_ethernet_down_color;
extern unsigned long bar_ip_color;
extern unsigned long bar_ip_down_color;
extern unsigned long bar_battery_color;
extern unsigned long bar_cputemp_color;
extern unsigned long bar_disk_color;
extern unsigned int configured_ws_masks[MAX_MONITORS];
extern unsigned char configured_ws_mask_set[MAX_MONITORS];
extern char workspace_names[MAX_WORKSPACES][32];
extern char autostart_cmds[MAX_AUTOSTART][256];
extern int autostart_count;
extern FocusPolicy focus_policy;
extern Monitor *spawn_target_monitor;
extern time_t spawn_target_time;
extern XftFont *wm_xft_font;
extern XftDraw *wm_xft_draw;
extern XftColor wm_xft_color;
extern int wm_xft_color_valid;
extern Client *drag_client;
extern int drag_mode;
extern int drag_start_root_x;
extern int drag_start_root_y;
extern int drag_start_win_x;
extern int drag_start_win_y;
extern int drag_start_win_w;
extern int drag_start_win_h;
extern Client *scratchpad_client;

#endif
